#!/usr/bin/env bash
set -euo pipefail

AGENT_ID="operator"
WS="/Users/sawyer/.openclaw/workspace-operator"
CLAUDE_MD="$WS/CLAUDE.md"
BOOTSTRAP_MD="$WS/BOOTSTRAP.md"
IDENTITY_MD="$WS/IDENTITY.md"
USER_MD="$WS/USER.md"
TOOLS_MD="$WS/TOOLS.md"
HOOK_DIR="$WS/hooks/git"
COMMIT_HOOK="$HOOK_DIR/commit-msg"
PREPUSH_HOOK="$HOOK_DIR/pre-push"
AUDIT_SCRIPT="$WS/scripts/agent-attribution-audit.sh"

has_text() {
  local pattern="$1" file="$2"
  LC_ALL=C grep -Eiq "$pattern" "$file"
}

protocol=0
verification=0
attribution=0
notes=()
hard_fail=0

# --- PROTOCOL QUALITY (10) ---
if has_text "## Mission" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing mission section"); fi
if has_text "## Scope" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing scope section"); fi
if has_text "## Verification Expectations|## Verification Gates" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing verification expectations section"); fi
if has_text "## Escalation Triggers|## Safety and Escalation" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing escalation triggers section"); fi
if has_text "Universal Phase 2 Hardening" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing phase 2 hardening section"); fi
if [[ -f "$USER_MD" ]]; then :; else notes+=("protocol: missing USER.md"); hard_fail=1; fi
if [[ -f "$TOOLS_MD" ]]; then :; else notes+=("protocol: missing TOOLS.md"); hard_fail=1; fi

if [[ "$AGENT_ID" == "codex-orchestrator" ]]; then
  if has_text "10 active PRs|10-active-PR cap" "$CLAUDE_MD" && has_text "10 active PRs as a hard cap|10-active-PR cap" "$BOOTSTRAP_MD"; then
    :
  else
    notes+=("protocol: missing OpenClaw PR queue guard")
    hard_fail=1
  fi
fi

# --- VERIFICATION DISCIPLINE (10) ---
if has_text "verify before claiming completion|Verification Expectations|Verification Gates|prove findings and prove fixes|Re-run the relevant check after a fix" "$CLAUDE_MD"; then verification=$((verification+3)); else notes+=("verification: weak CLAUDE verification language"); fi
if has_text "Read CLAUDE\\.md when it exists|Read .*CLAUDE\\.md" "$BOOTSTRAP_MD"; then verification=$((verification+2)); else notes+=("verification: bootstrap missing CLAUDE read step"); fi
if has_text "outcome, evidence, risks/open questions, next move|outcome → evidence → risks/open questions → next move" "$BOOTSTRAP_MD"; then verification=$((verification+3)); else notes+=("verification: bootstrap missing reporting shape"); fi
if has_text "BUILD\\.md" "$BOOTSTRAP_MD"; then verification=$((verification+1)); else notes+=("verification: bootstrap missing BUILD.md discipline"); fi
if has_text "Verify before claiming completion" "$IDENTITY_MD"; then verification=$((verification+1)); else notes+=("verification: identity missing verification anchor"); fi

# --- ATTRIBUTION COMPLIANCE (10) ---
if [[ -x "$COMMIT_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: commit-msg hook missing/not executable"); fi
if [[ -x "$PREPUSH_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: pre-push hook missing/not executable"); fi
if [[ -x "$AUDIT_SCRIPT" ]]; then attribution=$((attribution+1)); else notes+=("attribution: audit script missing/not executable"); fi
if has_text "No commit metadata may reference agent names, assistants, or AI terms" "$BOOTSTRAP_MD"; then attribution=$((attribution+1)); else notes+=("attribution: bootstrap policy missing"); fi

# Synthetic commit message tests
tmp_ok="$(mktemp)"
tmp_bad="$(mktemp)"
printf 'fix(core): tighten validation path\n' > "$tmp_ok"
printf 'fix: generated by Claude\n\nCo-Authored-By: Bot <bot@example.com>\n' > "$tmp_bad"

if "$COMMIT_HOOK" "$tmp_ok" >/dev/null 2>&1; then attribution=$((attribution+3)); else notes+=("attribution: commit-msg hook failed valid message"); fi
if "$COMMIT_HOOK" "$tmp_bad" >/dev/null 2>&1; then notes+=("attribution: commit-msg hook failed to block invalid message"); else attribution=$((attribution+3)); fi
rm -f "$tmp_ok" "$tmp_bad"

overall=$(( (protocol + verification + attribution) / 3 ))
status="PASS"
if (( protocol < 8 || verification < 8 || attribution < 8 || hard_fail != 0 )); then
  status="FAIL"
fi

cat <<REPORT
## operator Weekly Specialist Smoke

| Category | Score (0-10) | Status |
|---|---:|---|
| Protocol quality | $protocol | $( ((protocol>=8)) && echo PASS || echo FAIL ) |
| Verification discipline | $verification | $( ((verification>=8)) && echo PASS || echo FAIL ) |
| Attribution compliance | $attribution | $( ((attribution>=8)) && echo PASS || echo FAIL ) |
| Overall | $overall | $status |

### Notes
REPORT

if ((${#notes[@]}==0)); then
  echo "- No issues detected"
else
  for n in "${notes[@]}"; do
    echo "- $n"
  done
fi

if [[ "$status" != "PASS" ]]; then
  exit 1
fi
