import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { logStep } from "../common";

const HOME = process.env.HOME ?? homedir();
const OPENCLAW_ROOT = join(HOME, ".openclaw");

const MANAGED_SPECIALISTS = [
  "samantha",
  "sentinel",
  "shipwright",
  "caretaker",
  "archivist",
  "scout",
  "operator",
  "reviewer",
  "builder-mobile",
] as const;

const BOOTSTRAP_TEMPLATE = `# BOOTSTRAP.md

Session bootstrap checklist:

1. Read \`SOUL.md\`.
2. Read \`AGENTS.md\`.
3. Read \`CLAUDE.md\` (role mission + constraints).
4. Read task-relevant docs/files only.
5. Verify model/runtime context (\`/status\` or session metadata).
6. For risky actions, pause and ask before executing.
7. Report with: decision first, evidence second, next step third.

Operational notes:
- Workspace copy of \`SOUL.md\` and \`AGENTS.md\` is canonical.
- Keep \`grimoire\` copies in sync after canonical edits.
- Prefer smallest reliable change + explicit verification.
- No commit metadata may reference agent names, assistants, or AI terms.
- Before repo implementation work, set \`core.hooksPath\` to this workspace hook dir.
`;

const COMMIT_HOOK = `#!/usr/bin/env bash
set -euo pipefail

MSG_FILE="${"${1:-}"}"
if [[ -z "$MSG_FILE" || ! -f "$MSG_FILE" ]]; then
  echo "commit-msg hook: missing commit message file" >&2
  exit 2
fi

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'

if LC_ALL=C grep -Einq "$FORBIDDEN_RE" "$MSG_FILE"; then
  echo "❌ Commit message blocked: forbidden attribution/reference detected." >&2
  echo "Forbidden terms: Claude, Scry, assistant, AI, Co-Authored-By, generated by, authored by" >&2
  echo "--- offending lines ---" >&2
  LC_ALL=C grep -Ein "$FORBIDDEN_RE" "$MSG_FILE" >&2 || true
  exit 1
fi

exit 0
`;

const PRE_PUSH_HOOK = `#!/usr/bin/env bash
set -euo pipefail

remote_name="${"${1:-origin}"}"
remote_url="${"${2:-}"}"

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'
violations=0

echo "specialist pre-push audit: scanning outgoing commit messages..." >&2

while read -r local_ref local_sha remote_ref remote_sha; do
  [[ -z "${"${local_ref:-}"}" ]] && continue

  if [[ "$local_sha" == "0000000000000000000000000000000000000000" ]]; then
    continue
  fi

  if [[ "$remote_sha" == "0000000000000000000000000000000000000000" ]]; then
    commit_list=$(git rev-list "$local_sha" --not --remotes="$remote_name" 2>/dev/null || true)
  else
    commit_list=$(git rev-list "${"${remote_sha}..${local_sha}"}" 2>/dev/null || true)
  fi

  for sha in $commit_list; do
    msg=$(git log -1 --pretty=%B "$sha")
    if printf '%s' "$msg" | LC_ALL=C grep -Einq "$FORBIDDEN_RE"; then
      echo "❌ Forbidden attribution in commit $sha" >&2
      printf '%s\\n' "$msg" | LC_ALL=C grep -Ein "$FORBIDDEN_RE" >&2 || true
      violations=1
    fi
  done
done

if [[ "$violations" -ne 0 ]]; then
  echo "Push blocked. Rewrite commit messages and retry." >&2
  exit 1
fi

echo "✅ pre-push audit passed" >&2
exit 0
`;

const AUDIT_SCRIPT = `#!/usr/bin/env bash
set -euo pipefail

REPO="${"${1:-}"}"
BASE_REF="${"${2:-origin/main}"}"

if [[ -z "$REPO" ]]; then
  echo "Usage: $0 <repo-path> [base-ref]" >&2
  exit 2
fi

if [[ ! -d "$REPO/.git" ]]; then
  echo "Repo not found or not a git repo: $REPO" >&2
  exit 2
fi

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'

cd "$REPO"

echo "== Specialist Attribution Audit =="
echo "repo: $REPO"
echo "base: $BASE_REF"

git fetch --all --prune >/dev/null 2>&1 || true

range="${"${BASE_REF}..HEAD"}"
commits=$(git rev-list "$range" 2>/dev/null || true)

if [[ -z "$commits" ]]; then
  echo "No commits ahead of $BASE_REF on current branch."
  exit 0
fi

echo "Scanning commit messages in $range"
violations=0
for sha in $commits; do
  msg=$(git log -1 --pretty=%B "$sha")
  if printf '%s' "$msg" | LC_ALL=C grep -Einq "$FORBIDDEN_RE"; then
    echo "[FAIL] $sha"
    printf '%s\\n' "$msg" | LC_ALL=C grep -Ein "$FORBIDDEN_RE" || true
    violations=1
  fi
done

if [[ "$violations" -ne 0 ]]; then
  echo "Audit failed: forbidden attribution terms detected."
  exit 1
fi

echo "Audit passed: no forbidden attribution terms detected."
`;

function universalHardeningSection(agentId: string): string {
  return `<!-- SPECIALIST_PHASE2_START -->
## Universal Phase 2 Hardening

### Commit Metadata Guard (no attribution)
- Never include assistant/agent attribution in commit metadata.
- Forbidden in commit title/body/trailers: \`Claude\`, \`Scry\`, \`AI\`, \`assistant\`, \`Co-Authored-By\`, \`generated by\`, \`authored by\`.

### Hook Enforcement (required per repo)
Before implementation in any repo, wire hooks:

\`\`\`bash
git -C <repo> config core.hooksPath /Users/sawyer/.openclaw/workspace-${agentId}/hooks/git
\`\`\`

### Local Audit Command
Run before push when there are branch commits:

\`\`\`bash
/Users/sawyer/.openclaw/workspace-${agentId}/scripts/agent-attribution-audit.sh <repo> origin/main
\`\`\`

### Weekly Quality Smoke

\`\`\`bash
/Users/sawyer/.openclaw/workspace-${agentId}/scripts/specialist-weekly-smoke.sh
\`\`\`

Must pass all categories at >= 8/10.
<!-- SPECIALIST_PHASE2_END -->`;
}

function runbook(agentId: string, displayName: string): string {
  return `# RUNBOOK.md — ${displayName} Operations

## 1) Hook wiring check (target repo)
\`\`\`bash
git -C <repo> config --get core.hooksPath
\`\`\`
Expected:
\`/Users/sawyer/.openclaw/workspace-${agentId}/hooks/git\`

## 2) Manual attribution audit
\`\`\`bash
/Users/sawyer/.openclaw/workspace-${agentId}/scripts/agent-attribution-audit.sh <repo> origin/main
\`\`\`

## 3) Weekly scored smoke
\`\`\`bash
/Users/sawyer/.openclaw/workspace-${agentId}/scripts/specialist-weekly-smoke.sh
\`\`\`

Scored categories:
- Protocol quality (0-10)
- Verification discipline (0-10)
- Attribution compliance (0-10)

PASS threshold: each category >= 8.
`;
}

function smokeScript(agentId: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail

AGENT_ID="${agentId}"
WS="/Users/sawyer/.openclaw/workspace-${agentId}"
CLAUDE_MD="$WS/CLAUDE.md"
BOOTSTRAP_MD="$WS/BOOTSTRAP.md"
IDENTITY_MD="$WS/IDENTITY.md"
HOOK_DIR="$WS/hooks/git"
COMMIT_HOOK="$HOOK_DIR/commit-msg"
PREPUSH_HOOK="$HOOK_DIR/pre-push"
AUDIT_SCRIPT="$WS/scripts/agent-attribution-audit.sh"

has_text() {
  local pattern="$1" file="$2"
  LC_ALL=C grep -Eiq "$pattern" "$file"
}

protocol=0
verification=0
attribution=0
notes=()

# --- PROTOCOL QUALITY (10) ---
if has_text "## Mission" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing mission section"); fi
if has_text "## Scope" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing scope section"); fi
if has_text "## Verification Expectations" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing verification expectations section"); fi
if has_text "## Escalation Triggers" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing escalation triggers section"); fi
if has_text "Universal Phase 2 Hardening" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing phase 2 hardening section"); fi

# --- VERIFICATION DISCIPLINE (10) ---
if has_text "verify before claiming completion|Verification Expectations" "$CLAUDE_MD"; then verification=$((verification+3)); else notes+=("verification: weak CLAUDE verification language"); fi
if has_text "Read .*CLAUDE\\.md" "$BOOTSTRAP_MD"; then verification=$((verification+3)); else notes+=("verification: bootstrap missing CLAUDE read step"); fi
if has_text "decision first, evidence second, next" "$BOOTSTRAP_MD"; then verification=$((verification+2)); else notes+=("verification: bootstrap missing reporting shape"); fi
if has_text "Verify before claiming completion" "$IDENTITY_MD"; then verification=$((verification+2)); else notes+=("verification: identity missing verification anchor"); fi

# --- ATTRIBUTION COMPLIANCE (10) ---
if [[ -x "$COMMIT_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: commit-msg hook missing/not executable"); fi
if [[ -x "$PREPUSH_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: pre-push hook missing/not executable"); fi
if [[ -x "$AUDIT_SCRIPT" ]]; then attribution=$((attribution+1)); else notes+=("attribution: audit script missing/not executable"); fi
if has_text "No commit metadata may reference agent names, assistants, or AI terms" "$BOOTSTRAP_MD"; then attribution=$((attribution+1)); else notes+=("attribution: bootstrap policy missing"); fi

# Synthetic commit message tests
tmp_ok="$(mktemp)"
tmp_bad="$(mktemp)"
printf 'fix(core): tighten validation path\\n' > "$tmp_ok"
printf 'fix: generated by Claude\\n\\nCo-Authored-By: Bot <bot@example.com>\\n' > "$tmp_bad"

if "$COMMIT_HOOK" "$tmp_ok" >/dev/null 2>&1; then attribution=$((attribution+3)); else notes+=("attribution: commit-msg hook failed valid message"); fi
if "$COMMIT_HOOK" "$tmp_bad" >/dev/null 2>&1; then notes+=("attribution: commit-msg hook failed to block invalid message"); else attribution=$((attribution+3)); fi
rm -f "$tmp_ok" "$tmp_bad"

overall=$(( (protocol + verification + attribution) / 3 ))
status="PASS"
if (( protocol < 8 || verification < 8 || attribution < 8 )); then
  status="FAIL"
fi

cat <<REPORT
## ${agentId} Weekly Specialist Smoke

| Category | Score (0-10) | Status |
|---|---:|---|
| Protocol quality | $protocol | $( ((protocol>=8)) && echo PASS || echo FAIL ) |
| Verification discipline | $verification | $( ((verification>=8)) && echo PASS || echo FAIL ) |
| Attribution compliance | $attribution | $( ((attribution>=8)) && echo PASS || echo FAIL ) |
| Overall | $overall | $status |

### Notes
REPORT

if ((${"${#notes[@]}"}==0)); then
  echo "- No issues detected"
else
  for n in "${"${notes[@]}"}"; do
    echo "- $n"
  done
fi

if [[ "$status" != "PASS" ]]; then
  exit 1
fi
`;
}

function ensureDir(path: string): void {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true });
  }
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (existing === content) return false;
  }
  writeFileSync(path, content, "utf8");
  return true;
}

function appendIdentityLine(path: string): boolean {
  const line =
    "- Commit metadata must never include assistant/agent/AI attribution terms.";
  const current = readFileSync(path, "utf8");
  if (current.includes(line)) return false;
  const next = `${current.trimEnd()}\n${line}\n`;
  writeFileSync(path, next, "utf8");
  return true;
}

function upsertHardeningSection(path: string, section: string): boolean {
  const current = readFileSync(path, "utf8");

  const start = "<!-- SPECIALIST_PHASE2_START -->";
  const end = "<!-- SPECIALIST_PHASE2_END -->";
  if (current.includes(start) && current.includes(end)) {
    const prefix = current.split(start)[0].trimEnd();
    const suffix = current.split(end)[1] ?? "";
    const next = `${prefix}\n\n${section}\n${suffix.replace(/^\n+/, "")}`;
    if (next === current) return false;
    writeFileSync(path, next, "utf8");
    return true;
  }

  if (current.includes("## Universal Phase 2 Hardening")) {
    const prefix = current.split("## Universal Phase 2 Hardening")[0].trimEnd();
    const next = `${prefix}\n\n${section}\n`;
    if (next === current) return false;
    writeFileSync(path, next, "utf8");
    return true;
  }

  const next = `${current.trimEnd()}\n\n${section}\n`;
  writeFileSync(path, next, "utf8");
  return true;
}

function displayName(agentId: string): string {
  if (agentId === "builder-mobile") return "Builder Mobile";
  return agentId.charAt(0).toUpperCase() + agentId.slice(1);
}

function resolveTargets(): string[] {
  const includeMaintainer = Bun.argv.includes("--include-maintainer");

  const argAgents = Bun.argv.find((a) => a.startsWith("--agents="));
  if (argAgents) {
    const value = argAgents.split("=")[1]?.trim() ?? "";
    const explicit = value
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    if (includeMaintainer) return explicit;
    return explicit.filter((id) => id !== "openclaw-maintainer");
  }

  if (Bun.argv.includes("--discover")) {
    const dirs = readdirSync(OPENCLAW_ROOT, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name.startsWith("workspace-"))
      .map((d) => d.name.replace(/^workspace-/, ""))
      .filter((id) => !["claude", "codex", "main"].includes(id))
      .filter((id) => includeMaintainer || id !== "openclaw-maintainer");
    return dirs.sort();
  }

  return [...MANAGED_SPECIALISTS];
}

export function hardenSpecialists(): void {
  const targets = resolveTargets();
  if (targets.length === 0) {
    console.log("No specialist targets resolved.");
    return;
  }

  logStep(`Hardening specialist workspaces (${targets.join(", ")})`);

  let writes = 0;

  for (const agentId of targets) {
    const ws = join(OPENCLAW_ROOT, `workspace-${agentId}`);
    if (!existsSync(ws)) {
      console.log(`  [SKIP] ${agentId}: workspace not found (${ws})`);
      continue;
    }

    const hooksDir = join(ws, "hooks", "git");
    const scriptsDir = join(ws, "scripts");

    ensureDir(hooksDir);
    ensureDir(scriptsDir);

    if (writeIfChanged(join(hooksDir, "commit-msg"), COMMIT_HOOK)) writes++;
    if (writeIfChanged(join(hooksDir, "pre-push"), PRE_PUSH_HOOK)) writes++;
    if (
      writeIfChanged(
        join(scriptsDir, "agent-attribution-audit.sh"),
        AUDIT_SCRIPT,
      )
    )
      writes++;
    if (
      writeIfChanged(
        join(scriptsDir, "specialist-weekly-smoke.sh"),
        smokeScript(agentId),
      )
    )
      writes++;

    chmodSync(join(hooksDir, "commit-msg"), 0o700);
    chmodSync(join(hooksDir, "pre-push"), 0o700);
    chmodSync(join(scriptsDir, "agent-attribution-audit.sh"), 0o700);
    chmodSync(join(scriptsDir, "specialist-weekly-smoke.sh"), 0o700);

    const bootstrapPath = join(ws, "BOOTSTRAP.md");
    const identityPath = join(ws, "IDENTITY.md");
    const claudePath = join(ws, "CLAUDE.md");
    const runbookPath = join(ws, "RUNBOOK.md");

    if (existsSync(bootstrapPath)) {
      if (writeIfChanged(bootstrapPath, BOOTSTRAP_TEMPLATE)) writes++;
    }

    if (existsSync(identityPath)) {
      if (appendIdentityLine(identityPath)) writes++;
    }

    if (existsSync(claudePath)) {
      if (
        upsertHardeningSection(claudePath, universalHardeningSection(agentId))
      )
        writes++;
    }

    if (writeIfChanged(runbookPath, runbook(agentId, displayName(agentId))))
      writes++;

    console.log(`  [OK] ${agentId}`);
  }

  logStep("Specialist hardening complete");
  console.log(`  files updated: ${writes}`);
  console.log("  note: run specialist weekly smokes to verify scores");
}
