"""Generate and deploy Phase 2 hardening assets to specialist agent workspaces.

Rolls out: git hooks (commit-msg, pre-push), audit script, weekly smoke script,
BOOTSTRAP.md template, CLAUDE.md hardening section, IDENTITY.md attribution line,
and RUNBOOK.md per specialist.

Usage:
  uv run python -m scripts specialists:harden
  uv run python -m scripts specialists:harden --discover
  uv run python -m scripts specialists:harden --agents=samantha,sentinel
  uv run python -m scripts specialists:harden --include-maintainer
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from scripts.common import log_step

HOME = os.environ.get("HOME", str(Path.home()))
OPENCLAW_ROOT = Path(HOME) / ".openclaw"

MANAGED_SPECIALISTS = [
    "sentinel",
    "reviewer",
    "builder-mobile",
]


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

BOOTSTRAP_TEMPLATE = """# BOOTSTRAP.md

Session bootstrap checklist:

1. Read `SOUL.md`.
2. Read `AGENTS.md`.
3. Read `CLAUDE.md` (role mission + constraints).
4. Read task-relevant docs/files only.
5. Verify model/runtime context (`/status` or session metadata).
6. For risky actions, pause and ask before executing.
7. Report with: decision first, evidence second, next step third.

Operational notes:
- Workspace copy of `SOUL.md` and `AGENTS.md` is canonical.
- Keep `grimoire` copies in sync after canonical edits.
- Prefer smallest reliable change + explicit verification.
- No commit metadata may reference agent names, assistants, or AI terms.
- Before repo implementation work, set `core.hooksPath` to this workspace hook dir.
"""


def _commit_hook() -> str:
    return r"""#!/usr/bin/env bash
set -euo pipefail

MSG_FILE="${1:-}"
if [[ -z "$MSG_FILE" || ! -f "$MSG_FILE" ]]; then
  echo "commit-msg hook: missing commit message file" >&2
  exit 2
fi

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'

if LC_ALL=C grep -Einq "$FORBIDDEN_RE" "$MSG_FILE"; then
  echo "❌ Commit message blocked: forbidden attribution/reference detected." >&2
  echo "Forbidden terms: Claude, Scry, assistant, AI, Co-Authored-By, generated by, authored by" >&2
  echo "--- offending lines ---" >&2
  LC_ALL=C grep -Ein "$FORBIDDEN_RE" "$MSG_FILE" >&2 || true
  exit 1
fi

exit 0
"""


def _pre_push_hook() -> str:
    return r"""#!/usr/bin/env bash
set -euo pipefail

remote_name="${1:-origin}"
remote_url="${2:-}"

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'
violations=0

echo "specialist pre-push audit: scanning outgoing commit messages..." >&2

while read -r local_ref local_sha remote_ref remote_sha; do
  [[ -z "${local_ref:-}" ]] && continue

  if [[ "$local_sha" == "0000000000000000000000000000000000000000" ]]; then
    continue
  fi

  if [[ "$remote_sha" == "0000000000000000000000000000000000000000" ]]; then
    commit_list=$(git rev-list "$local_sha" --not --remotes="$remote_name" 2>/dev/null || true)
  else
    commit_list=$(git rev-list "${remote_sha}..${local_sha}" 2>/dev/null || true)
  fi

  for sha in $commit_list; do
    msg=$(git log -1 --pretty=%B "$sha")
    if printf '%s' "$msg" | LC_ALL=C grep -Einq "$FORBIDDEN_RE"; then
      echo "❌ Forbidden attribution in commit $sha" >&2
      printf '%s\n' "$msg" | LC_ALL=C grep -Ein "$FORBIDDEN_RE" >&2 || true
      violations=1
    fi
  done
done

if [[ "$violations" -ne 0 ]]; then
  echo "Push blocked. Rewrite commit messages and retry." >&2
  exit 1
fi

echo "✅ pre-push audit passed" >&2
exit 0
"""


def _audit_script() -> str:
    return r"""#!/usr/bin/env bash
set -euo pipefail

REPO="${1:-}"
BASE_REF="${2:-origin/main}"

if [[ -z "$REPO" ]]; then
  echo "Usage: $0 <repo-path> [base-ref]" >&2
  exit 2
fi

if [[ ! -d "$REPO/.git" ]]; then
  echo "Repo not found or not a git repo: $REPO" >&2
  exit 2
fi

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'

cd "$REPO"

echo "== Specialist Attribution Audit =="
echo "repo: $REPO"
echo "base: $BASE_REF"

git fetch --all --prune >/dev/null 2>&1 || true

range="${BASE_REF}..HEAD"
commits=$(git rev-list "$range" 2>/dev/null || true)

if [[ -z "$commits" ]]; then
  echo "No commits ahead of $BASE_REF on current branch."
  exit 0
fi

echo "Scanning commit messages in $range"
violations=0
for sha in $commits; do
  msg=$(git log -1 --pretty=%B "$sha")
  if printf '%s' "$msg" | LC_ALL=C grep -Einq "$FORBIDDEN_RE"; then
    echo "[FAIL] $sha"
    printf '%s\n' "$msg" | LC_ALL=C grep -Ein "$FORBIDDEN_RE" || true
    violations=1
  fi
done

if [[ "$violations" -ne 0 ]]; then
  echo "Audit failed: forbidden attribution terms detected."
  exit 1
fi

echo "Audit passed: no forbidden attribution terms detected."
"""


def _smoke_script(agent_id: str) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

AGENT_ID="{agent_id}"
WS="/Users/sawyer/.openclaw/workspace-{agent_id}"
CLAUDE_MD="$WS/CLAUDE.md"
BOOTSTRAP_MD="$WS/BOOTSTRAP.md"
IDENTITY_MD="$WS/IDENTITY.md"
HOOK_DIR="$WS/hooks/git"
COMMIT_HOOK="$HOOK_DIR/commit-msg"
PREPUSH_HOOK="$HOOK_DIR/pre-push"
AUDIT_SCRIPT="$WS/scripts/agent-attribution-audit.sh"

has_text() {{
  local pattern="$1" file="$2"
  LC_ALL=C grep -Eiq "$pattern" "$file"
}}

protocol=0
verification=0
attribution=0
notes=()

# --- PROTOCOL QUALITY (10) ---
if has_text "## Mission" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing mission section"); fi
if has_text "## Scope" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing scope section"); fi
if has_text "## Verification Expectations" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing verification expectations section"); fi
if has_text "## Escalation Triggers" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing escalation triggers section"); fi
if has_text "Universal Phase 2 Hardening" "$CLAUDE_MD"; then protocol=$((protocol+2)); else notes+=("protocol: missing phase 2 hardening section"); fi

# --- VERIFICATION DISCIPLINE (10) ---
if has_text "verify before claiming completion|Verification Expectations" "$CLAUDE_MD"; then verification=$((verification+3)); else notes+=("verification: weak CLAUDE verification language"); fi
if has_text "Read .*CLAUDE\\\\.md" "$BOOTSTRAP_MD"; then verification=$((verification+3)); else notes+=("verification: bootstrap missing CLAUDE read step"); fi
if has_text "decision first, evidence second, next" "$BOOTSTRAP_MD"; then verification=$((verification+2)); else notes+=("verification: bootstrap missing reporting shape"); fi
if has_text "Verify before claiming completion" "$IDENTITY_MD"; then verification=$((verification+2)); else notes+=("verification: identity missing verification anchor"); fi

# --- ATTRIBUTION COMPLIANCE (10) ---
if [[ -x "$COMMIT_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: commit-msg hook missing/not executable"); fi
if [[ -x "$PREPUSH_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: pre-push hook missing/not executable"); fi
if [[ -x "$AUDIT_SCRIPT" ]]; then attribution=$((attribution+1)); else notes+=("attribution: audit script missing/not executable"); fi
if has_text "No commit metadata may reference agent names, assistants, or AI terms" "$BOOTSTRAP_MD"; then attribution=$((attribution+1)); else notes+=("attribution: bootstrap policy missing"); fi

# Synthetic commit message tests
tmp_ok="$(mktemp)"
tmp_bad="$(mktemp)"
printf 'fix(core): tighten validation path\\n' > "$tmp_ok"
printf 'fix: generated by Claude\\n\\nCo-Authored-By: Bot <bot@example.com>\\n' > "$tmp_bad"

if "$COMMIT_HOOK" "$tmp_ok" >/dev/null 2>&1; then attribution=$((attribution+3)); else notes+=("attribution: commit-msg hook failed valid message"); fi
if "$COMMIT_HOOK" "$tmp_bad" >/dev/null 2>&1; then notes+=("attribution: commit-msg hook failed to block invalid message"); else attribution=$((attribution+3)); fi
rm -f "$tmp_ok" "$tmp_bad"

overall=$(( (protocol + verification + attribution) / 3 ))
status="PASS"
if (( protocol < 8 || verification < 8 || attribution < 8 )); then
  status="FAIL"
fi

cat <<REPORT
## {agent_id} Weekly Specialist Smoke

| Category | Score (0-10) | Status |
|---|---:|---|
| Protocol quality | $protocol | $( ((protocol>=8)) && echo PASS || echo FAIL ) |
| Verification discipline | $verification | $( ((verification>=8)) && echo PASS || echo FAIL ) |
| Attribution compliance | $attribution | $( ((attribution>=8)) && echo PASS || echo FAIL ) |
| Overall | $overall | $status |

### Notes
REPORT

if ((${{#notes[@]}}==0)); then
  echo "- No issues detected"
else
  for n in "${{notes[@]}}"; do
    echo "- $n"
  done
fi

if [[ "$status" != "PASS" ]]; then
  exit 1
fi
"""


def _universal_hardening_section(agent_id: str) -> str:
    return f"""<!-- SPECIALIST_PHASE2_START -->
## Universal Phase 2 Hardening

### Commit Metadata Guard (no attribution)
- Never include assistant/agent attribution in commit metadata.
- Forbidden in commit title/body/trailers: `Claude`, `Scry`, `AI`, `assistant`, `Co-Authored-By`, `generated by`, `authored by`.

### Hook Enforcement (required per repo)
Before implementation in any repo, wire hooks:

```bash
git -C <repo> config core.hooksPath /Users/sawyer/.openclaw/workspace-{agent_id}/hooks/git
```

### Local Audit Command
Run before push when there are branch commits:

```bash
/Users/sawyer/.openclaw/workspace-{agent_id}/scripts/agent-attribution-audit.sh <repo> origin/main
```

### Weekly Quality Smoke

```bash
/Users/sawyer/.openclaw/workspace-{agent_id}/scripts/specialist-weekly-smoke.sh
```

Must pass all categories at >= 8/10.
<!-- SPECIALIST_PHASE2_END -->"""


def _runbook(agent_id: str, display_name: str) -> str:
    return f"""# RUNBOOK.md — {display_name} Operations

## 1) Hook wiring check (target repo)
```bash
git -C <repo> config --get core.hooksPath
```
Expected:
`/Users/sawyer/.openclaw/workspace-{agent_id}/hooks/git`

## 2) Manual attribution audit
```bash
/Users/sawyer/.openclaw/workspace-{agent_id}/scripts/agent-attribution-audit.sh <repo> origin/main
```

## 3) Weekly scored smoke
```bash
/Users/sawyer/.openclaw/workspace-{agent_id}/scripts/specialist-weekly-smoke.sh
```

Scored categories:
- Protocol quality (0-10)
- Verification discipline (0-10)
- Attribution compliance (0-10)

PASS threshold: each category >= 8.
"""


def _display_name(agent_id: str) -> str:
    if agent_id == "builder-mobile":
        return "Builder Mobile"
    return agent_id[0].upper() + agent_id[1:]


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        existing = path.read_text()
        if existing == content:
            return False
    path.write_text(content)
    return True


def _append_identity_line(path: Path) -> bool:
    line = "- Commit metadata must never include assistant/agent/AI attribution terms."
    current = path.read_text()
    if line in current:
        return False
    path.write_text(f"{current.rstrip()}\n{line}\n")
    return True


def _upsert_hardening_section(path: Path, section: str) -> bool:
    current = path.read_text()

    start = "<!-- SPECIALIST_PHASE2_START -->"
    end = "<!-- SPECIALIST_PHASE2_END -->"

    if start in current and end in current:
        prefix = current.split(start)[0].rstrip()
        suffix = current.split(end)[1].lstrip("\n") if end in current else ""
        next_content = f"{prefix}\n\n{section}\n{suffix}"
        if next_content == current:
            return False
        path.write_text(next_content)
        return True

    if "## Universal Phase 2 Hardening" in current:
        prefix = current.split("## Universal Phase 2 Hardening")[0].rstrip()
        next_content = f"{prefix}\n\n{section}\n"
        if next_content == current:
            return False
        path.write_text(next_content)
        return True

    path.write_text(f"{current.rstrip()}\n\n{section}\n")
    return True


# ---------------------------------------------------------------------------
# Target resolution
# ---------------------------------------------------------------------------


def _resolve_targets() -> list[str]:
    include_maintainer = "--include-maintainer" in sys.argv

    agents_arg = next((a for a in sys.argv if a.startswith("--agents=")), None)
    if agents_arg:
        value = agents_arg.split("=", 1)[1].strip()
        explicit = [s.strip() for s in value.split(",") if s.strip()]
        if include_maintainer:
            return explicit
        return [a for a in explicit if a != "openclaw-maintainer"]

    if "--discover" in sys.argv:
        dirs = sorted(
            d.name.removeprefix("workspace-")
            for d in OPENCLAW_ROOT.iterdir()
            if d.is_dir()
            and d.name.startswith("workspace-")
            and d.name.removeprefix("workspace-") not in ("claude", "codex", "main")
            and (
                include_maintainer
                or d.name.removeprefix("workspace-") != "openclaw-maintainer"
            )
        )
        return dirs

    return list(MANAGED_SPECIALISTS)


# ---------------------------------------------------------------------------
# Entry
# ---------------------------------------------------------------------------


def harden_specialists() -> None:
    targets = _resolve_targets()
    if not targets:
        print("No specialist targets resolved.")
        return

    log_step(f"Hardening specialist workspaces ({', '.join(targets)})")

    writes = 0

    for agent_id in targets:
        ws = OPENCLAW_ROOT / f"workspace-{agent_id}"
        if not ws.exists():
            print(f"  [SKIP] {agent_id}: workspace not found ({ws})")
            continue

        hooks_dir = ws / "hooks" / "git"
        scripts_dir = ws / "scripts"

        hooks_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir.mkdir(parents=True, exist_ok=True)

        if _write_if_changed(hooks_dir / "commit-msg", _commit_hook()):
            writes += 1
        if _write_if_changed(hooks_dir / "pre-push", _pre_push_hook()):
            writes += 1
        if _write_if_changed(
            scripts_dir / "agent-attribution-audit.sh", _audit_script()
        ):
            writes += 1
        if _write_if_changed(
            scripts_dir / "specialist-weekly-smoke.sh", _smoke_script(agent_id)
        ):
            writes += 1

        (hooks_dir / "commit-msg").chmod(0o700)
        (hooks_dir / "pre-push").chmod(0o700)
        (scripts_dir / "agent-attribution-audit.sh").chmod(0o700)
        (scripts_dir / "specialist-weekly-smoke.sh").chmod(0o700)

        bootstrap_path = ws / "BOOTSTRAP.md"
        identity_path = ws / "IDENTITY.md"
        claude_path = ws / "CLAUDE.md"
        runbook_path = ws / "RUNBOOK.md"

        if bootstrap_path.exists() and _write_if_changed(bootstrap_path, BOOTSTRAP_TEMPLATE):
            writes += 1

        if identity_path.exists() and _append_identity_line(identity_path):
            writes += 1

        if claude_path.exists() and _upsert_hardening_section(
            claude_path, _universal_hardening_section(agent_id)
        ):
            writes += 1

        if _write_if_changed(runbook_path, _runbook(agent_id, _display_name(agent_id))):
            writes += 1

        print(f"  [OK] {agent_id}")

    log_step("Specialist hardening complete")
    print(f"  files updated: {writes}")
    print("  note: run specialist weekly smokes to verify scores")
