#!/usr/bin/env bash
set -euo pipefail

REPO="${1:-}"
BASE_REF="${2:-origin/main}"

if [[ -z "$REPO" ]]; then
  echo "Usage: $0 <repo-path> [base-ref]" >&2
  exit 2
fi

if [[ ! -d "$REPO/.git" ]]; then
  echo "Repo not found or not a git repo: $REPO" >&2
  exit 2
fi

FORBIDDEN_RE='(^|[^a-z])(claude|scry|assistant|ai)([^a-z]|$)|co-authored-by|generated by|authored by'

cd "$REPO"

echo "== Specialist Attribution Audit =="
echo "repo: $REPO"
echo "base: $BASE_REF"

git fetch --all --prune >/dev/null 2>&1 || true

range="${BASE_REF}..HEAD"
commits=$(git rev-list "$range" 2>/dev/null || true)

if [[ -z "$commits" ]]; then
  echo "No commits ahead of $BASE_REF on current branch."
  exit 0
fi

echo "Scanning commit messages in $range"
violations=0
for sha in $commits; do
  msg=$(git log -1 --pretty=%B "$sha")
  if printf '%s' "$msg" | LC_ALL=C grep -Einq "$FORBIDDEN_RE"; then
    echo "[FAIL] $sha"
    printf '%s\n' "$msg" | LC_ALL=C grep -Ein "$FORBIDDEN_RE" || true
    violations=1
  fi
done

if [[ "$violations" -ne 0 ]]; then
  echo "Audit failed: forbidden attribution terms detected."
  exit 1
fi

echo "Audit passed: no forbidden attribution terms detected."
